### ISSUE TITLE
Hiding hard-coded buttons for workspace and launcher

### ISSUE THREAD

**Issue by valters-tomsons** [nwg-piotr/nwg-dock#10]
Hi!

Is it possible to remove the workspace switcher and application launcher buttons from the dock?

**Comment by nwg-piotr** [comment]
Not a the moment. Would you like it to be an option?

**Comment by valters-tomsons** [comment]
Yes, that would be wonderful! :smile_cat:

**Comment by nwg-piotr** [comment]
OK, I'll add arguments to disable the buttons, when my current work is finished.
