### ISSUE TITLE
No icons for workspace switcher and drawer

### ISSUE THREAD

**Issue by Mrfiregem** [nwg-piotr/nwg-dock#15]
**Describe the bug**
When running `nwg-dock`, the icons for the ws and drawer aren't loaded, the two buttons become very thin, and do nothing when clicked.

**To Reproduce**
1. Download package from AUR or chaotic-aur
2. Run `nwg-dock`

**Expected behavior**
The svg icons installed with the program should be used, and the buttons should be functional.

**Screenshot**
![test](https://user-images.githubusercontent.com/5158194/130546019-20407734-c956-4d0e-a61c-fed8d4804905.png)
(Ingore the styling since there's no css file. Issue even if copying over the default css file.)

**Desktop (please complete the following information):**
 - Arch Linux
 - Go version: N/A for chaotic-aur, 1.17 for compiling from AUR
 - gtk-layer-shell version: 0.6.0

**Additional context**
```
Using auto-detected launcher command: 'nwg-drawer'
Copying file: /home/cheer/.config/nwg-dock/style.css
/home/cheer/.config/nwg-dock/style.css file not found, using GTK styling
(0x55980473d9a8,0xc000013ff0)
(0x55980473d9a8,0xc00027e080)

** (nwg-dock:758083): WARNING **: 21:24:55.737: gtk-layer-shell v0.6.0 may not work on GTK v3.24.30. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
refreshing...
(0x55980473d9a8,0xc000113e60)
(0x55980473d9a8,0xc000113ef0)
```

**Comment by nwg-piotr** [comment]
I'll be fixing another issue in this program tonight. Will take a look a this as well.

**Comment by nwg-piotr** [comment]
Well, I couldn't confirm. To reproduce the behaviour you described, I had to:

1. uninstall the AUR package (`/usr/share/nwg-drawer` folder content is being removed;
2. build and run the program as described in README, but **without the step 4** (`sudo make install`), which copies files to their desired locations.

After proper package installation you should have the `/usr/share/nwg-drawer/` folder with the files `hotspot.css` & `style.css`, and the `images` subfolder, containing 25 .svg files.

I didn't try the chaotic-aur package. Could it be the culprit?

**Comment by notthewave** [comment]
same problem with the local directory on void-linux
