### ISSUE TITLE
Support swaysome

### ISSUE THREAD

**Issue by asjur** [nwg-piotr/nwg-dock#16]
**Describe the bug**
Using the workspace switcher just goes between 1-X but when using Swaysome it changes workspaces so they are handled similarly to Awesome WM where each monitor has it's own set of workspaces. 

With Swaysome monitor 1 is prefixed with 0, and monitor 2 is prefixed with 1. So you have workspaces like 01,02 on monitor 1 and 11, 12, 13 on monitor 2.

https://git.hya.sk/nabos/swaysome

**To Reproduce**
1. Launch nwg-dock
2. Use workspace switcher

**Expected behavior**
With support I would like to see it use existing workspaces rather than just scrolling through numbers.

**Screenshots**
Not relevant

**Desktop (please complete the following information):**
Not relevant

**Additional context**
Not relevant

**Comment by nwg-piotr** [comment]
Closing due to no response.
