### ISSUE TITLE
Hotspot only exists on output with currently focused window

### ISSUE THREAD

**Issue by starun96** [nwg-piotr/nwg-dock#2]
## System

1. OS: Arch Linux (`5.11.11-arch1-1`)
2. Window Manager: Sway `v1.5.1`
3. Monitor Setup: 3 monitors (outputs)
4. Nwg-dock version: `0.1.0`
5. Nwg-dock arguments used: `-d`

## Issue

I have nwg-dock set to autohide. When I hover my cursor over the hotspot of output A while the currently focused window is in output B, then  nwg-dock appears on output B instead of output A, where I would instead expect. This is inconvenient because I have to first click on a window in an output before I can start using nwg-dock on that monitor.

## Expected Behavior

Nwg-dock should appear the output whose hotspot I hover over, regardless of which window is focused/active. 

## Additional Clarifications

By "focused" I mean the window has been clicked on and now has input focus. In my setup, the window has a border changing color upon focus.

**Comment by nwg-piotr** [comment]
I also use 3 displays, and the dock appears where it should. Could I see your sway config?

**Comment by nwg-piotr** [comment]
I'm about to PR and merge, which will close the issue. Feel free to reopen if it turns out not to help.

**Comment by starun96** [comment]
Just wanted to say that the fix solves my problem. Thanks!

**Comment by nwg-piotr** [comment]
Excellent, thank you!
