### ISSUE TITLE
river support

### ISSUE THREAD

**Issue by j-james** [nwg-piotr/nwg-dock#20]
nwg-dock appears to depend on a sway-specific feature, and  crashes when trying to run it on other Wayland compositors like [river](https://github.com/riverwm/river).

```sh
FATA[0000] Couldn't list tasks:$SWAYSOCK is empty
```

**Comment by nwg-piotr** [comment]
> Fully configurable (w/ command line arguments and css) dock, written in Go, aimed exclusively at sway Wayland compositor.

**Comment by j-james** [comment]
Ah, missed that, sorry!

**Comment by nwg-piotr** [comment]
Yes, this dock bases on sway IPC, so is useless anywhere else. I'd need the `river-status-unstable-v1` protocol, but I don't think it has golang bindings.

**Comment by szbergeron** [comment]
@nwg-piotr shouldn't most of the functionality for this be possible using foreign-toplevel-manager? That would allow for it to work on wayfire as well

**Comment by nwg-piotr** [comment]
Possibly, but I've never really looked into [go-wlroots](https://github.com/swaywm/go-wlroots), as all I needed so far were `gtk-layer-shell` bindings. All the shell project needs contributors - I'm just an after hours, hobbyist programmer.
