### ISSUE TITLE
Feature Request : Support labwc

### ISSUE THREAD

**Issue by gitpubber** [nwg-piotr/nwg-dock#22]
labwc is work-in-progress wlroots based compositor. It would be nice if nwg-dock support it.

https://github.com/labwc/labwc

**Comment by nwg-piotr** [comment]
Once I tried to install labwc from AUR, but failed...

For now the dock supports sway only, as it bases on sway IPC. There were requests to use a wlroot protocol instead, to support other compositors. Maybe I'll try one day, but no ETA.

**Comment by gitpubber** [comment]
How can I help to use wlr-taskbar protocol?

**Comment by nwg-piotr** [comment]
Feel free to contribute. But IMO all the code is too much hooked on sway ipc for it to make sense. Writing from scratch may turn out easier.
