### ISSUE TITLE
nwg-dock workspace switching by touch

### ISSUE THREAD

**Issue by jazn** [nwg-piotr/nwg-dock#26]
Hello.

I use nwg-dock together with waybars on a pineNote. 

The situation is that when I switch app using pressing pen or mouse on the app icon workspace is switched to proper one for the app.
However when I touch an icon on a screen with a finger, icon is highlighted but not switched to the app or workspace.

Is this intended? Is there an command line option to change it? 
If not where to start the change in a code to modify this behavior?

Thank for this app.
Jaźń.

**Comment by nwg-piotr** [comment]
The other icons have no `scroll-event` event connected.

**Comment by jazn** [comment]
NOTE: [here](https://github.com/nwg-piotr/nwg-dock/blob/13125a2a741f48473d34c6e2e9bff3e468674354/tools.go#L365) you use `gdk.EVENT_BUTTON_RELEASE` which is specified to be a **mouse** button press. I will check this later.

**Comment by nwg-piotr** [comment]
Because we make different use of left and right button. But yes, this may be used as well, though is more tricky.

**Comment by jazn** [comment]
I've checked that touching screen emits:
```
btnEvent.Type() == gdk.EVENT_TOUCH_BEGIN
btnEvent.Button() == 0 /*depends on numer of touching fingers*/
```
and releasing finger emits:
```
btnEvent.Type() == gdk.EVENT_TOUCH_END
btnEvent.Button() == 0 /*depends on numer of touching fingers*/
```

quick&dirty fix:
tools.go:
```
-                       if btnEvent.Type() == gdk.EVENT_BUTTON_RELEASE {
-                               if btnEvent.Button() == 1 {
+                       if ( btnEvent.Type() == gdk.EVENT_BUTTON_RELEASE || btnEvent.Type() == gdk.EVENT_TOUCH_END ) {
+                               if ( btnEvent.Button() == 1|| btnEvent.Type() == gdk.EVENT_TOUCH_END )  {
```
proves that is enough to switch workspace on touch.

**Comment by nwg-piotr** [comment]
Would you mind submitting a PR? I'm working on 2 other things at the time, so it may take several days, if you want me to change the code on my side.

**Comment by jazn** [comment]
I will prepare PR.

**Comment by nwg-piotr** [comment]
Merged & closed
