### ISSUE TITLE
Enhancement: hyprland support

### ISSUE THREAD

**Issue by EysseW** [nwg-piotr/nwg-dock#29]
Hi! I am running hyprland and I'd really like to be able to use this.

**Comment by nwg-piotr** [comment]
Hi,

The dock in its current state is based on the sway IPC. Adding support for other WMs would mean a lot of new code. Also we have [this rule](https://github.com/nwg-piotr/nwg-shell#support-for-other-wms).

**Comment by EysseW** [comment]
I am sorry, should've opened my eyes. I don't know what you mean by /dev/null though

**Comment by nwg-piotr** [comment]
I mean [/dev/null](https://en.wikipedia.org/wiki/Null_device), which figuratively means nowhere.

Short explanation: nwg-dock is a part of a larger project, which is mostly driven by a single developer. Some time ago I wanted my stuff to work everywhere (see: [nwg-launchers](https://github.com/nwg-piotr/nwg-launchers)), but every single thing gets much more complicated this way. So I decided to focus on what I use myself - sway. If some other programmer decides to contribute, and make some nwg-shell component usable on another WM, I'm all right with it. But I refuse to work on it myself.

**Comment by EysseW** [comment]
Understandable, have a nice day!

**Comment by nwg-piotr** [comment]
Thank you and all the best.
