### ISSUE TITLE
Compile fail on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by jasek5** [nwg-piotr/nwg-dock#33]
**Describe the bug**
During command `make build` I get following error (2):
` nwg-dock git:(main) ✗ make build
go build -o bin/nwg-dock .
\# github.com/gotk3/gotk3/glib
cgo-gcc-prolog: In function ‘_cgo_200740c87a77_Cfunc_g_binding_get_source’:
cgo-gcc-prolog:71:2: warning: ‘g_binding_get_source’ is deprecated: Use 'g_binding_dup_source' instead [-Wdeprecated-declarations]
In file included from /usr/include/glib-2.0/glib-object.h:24,
                 from /usr/include/glib-2.0/gio/gioenums.h:30,
                 from /usr/include/glib-2.0/gio/giotypes.h:30,
                 from /usr/include/glib-2.0/gio/gio.h:28,
                 from ../go/pkg/mod/github.com/gotk3/gotk3@v0.6.1/glib/gbinding.go:3:
/usr/include/glib-2.0/gobject/gbinding.h:115:23: note: declared here
  115 | GObject *             g_binding_get_source          (GBinding *binding);
      |                       ^~~~~~~~~~~~~~~~~~~~
cgo-gcc-prolog: In function ‘_cgo_200740c87a77_Cfunc_g_binding_get_target’:
cgo-gcc-prolog:107:2: warning: ‘g_binding_get_target’ is deprecated: Use 'g_binding_dup_target' instead [-Wdeprecated-declarations]
/usr/include/glib-2.0/gobject/gbinding.h:119:23: note: declared here
  119 | GObject *             g_binding_get_target          (GBinding *binding);
      |                       ^~~~~~~~~~~~~~~~~~~~
\# github.com/nwg-piotr/nwg-dock
./tools.go:69:12: cannot use window.Change (variable of type sway.WindowEventChange) as type string in struct literal
./tools.go:87:33: cannot use eventHandler (variable of type swayEventHandler) as type sway.EventHandler in argument to sway.Subscribe:
	swayEventHandler does not implement sway.EventHandler (missing BarStateUpdate method)
./tools.go:117:33: cannot use eventHandler (variable of type swayEventHandler) as type sway.EventHandler in argument to sway.Subscribe:
	swayEventHandler does not implement sway.EventHandler (missing BarStateUpdate method)
make: *** [Makefile:11: build] Error 2`

**To Reproduce**
1. Clone repository
2. cd into repository folder
3. run command `make get`
4. run command `make build`
5. See the error

**Expected behavior**
I expect succesful build to proceed to running command `sudo make install`

**Screenshots**
![2022-11-21-070010_screenshot](https://user-images.githubusercontent.com/12669491/202976537-1b93d078-6135-4a5a-99b0-a43ecb8e8bdf.png)

**Desktop (please complete the following information):**
 - Linux distribution :  openSUSE Tumbleweed x86_64 
 - go version : go version go1.19.3 linux/amd64
 - gtk-layer-shell version:  0.8.0-1.1

**Comment by nwg-piotr** [comment]
A temporary solution: 

In go.mod, change the go version to 1.16, then `go mod tidy`.

On my machine at home it did build, but now at the office I'm getting into trouble, too. Will take a closer look when I'm back home.

**Comment by nwg-piotr** [comment]
Anyway, it needs to be fixed, together with updating the go-sway version. But I'm addicted to IDEs, and have none at the office. :D

**Comment by nwg-piotr** [comment]
Could you, please, try and build from the [update-go-sway](https://github.com/nwg-piotr/nwg-dock/tree/update-go-sway) branch?

**Comment by nwg-piotr** [comment]
Excellent. I'll merge and release later tonight. Thanks for confirmation.
