### ISSUE TITLE
[Workaround] [enhancement] Temporarily point AUR PKGBUILD to parallelized cgo fork

### ISSUE THREAD

**Issue by 154pinkchairs** [nwg-piotr/nwg-dock#39]
**Description**
For faster compilation of GTK3 bindings and given that AUR is, after all, a bleeding edge ground, PKGBUILD can point to the Go fork with parallelized cgo builds. It's quite disappointing that on Ryzen 9 7900X, the compilation of glib bindings alone takes over a minute. What I'm referring to is the fork created here:
https://github.com/Evengard/go/tree/go-cgo-gcc-parallelism-1.20.3

which I found on this issue page:
https://github.com/golang/go/issues/9887

**Caveats, alternative solutions**
I know the security and stability risks related to relying on 3rd party forks. Therefore alternatively, we can also try creating a separate AUR package (e.g. with `-parallel-cgo` suffix), which would use the aforementioned fork. 

This issue should also probably remain open, lest the changes get finally merged upstream and such a contraption is no longer needed.

**Desktop:**
 - OS: Artix OpenRC 6.3.6-zen1-1-zen
 - go version: 1.20.5 linux/amd64
 - gtk-layer-shell version: 0.8.1-1

**Comment by nwg-piotr** [comment]
What it means to me is maintaining 5 new packages, for nwg-drawer, nwg-menu, nwg-dock, nwg-dock-hyprland and nwg-look, while I already maintain a regular and -bin version of each above. I don't have enough time for this, but I don't mind you taking care of it.

**Comment by 154pinkchairs** [comment]
hmm yeah, I found the binary packages meanwhile, nevermind. hope this becomes oficially supported soon.

**Comment by nwg-piotr** [comment]
> hope this becomes oficially supported soon.

I do hope so, too.
