### ISSUE TITLE
Hotspot styling?

### ISSUE THREAD

**Issue by clanktron** [nwg-piotr/nwg-dock#46]
Is it possible to directly style the hotspot? In the repo there seems to be a `hotspot.css` but upon adding that to my config folder it doesn't seem to be used. I also tried styling the hotspot in the `style.css` like so:
```
#hotspot {
    background: #FFFFFF;
}
```
Right now it just ends up being styled however I style the `window`. I use the autohide feature and its annoying to have the hotspot stay as a black bar on the side of the screen.

![20240822_22h09m22s_grim](https://github.com/user-attachments/assets/09640034-4d34-4939-a862-0db1a739a984)

**Comment by nwg-piotr** [comment]
You could edit /usr/share/nwg-dock/hotspot.css. However, it'll be ovewritten at the next package update.

![obraz](https://github.com/user-attachments/assets/98624c83-bf96-4f4a-9ca2-bf7a1d2dcb46)

**Comment by clanktron** [comment]
Would you be open to reading a hotspot.css from the xdg_config folder? I could throw together a PR sometime soonish if you didn't want to bother adding the feature yourself.

**Comment by nwg-piotr** [comment]
Well, if I wanted people to edit it, I wouldn't had made a separate, hidden css file. :)

**Comment by clanktron** [comment]
okay...is there some technical reason you don't want people changing it?

I don't necessarily need to have custom css for the hotspot if you don't want that I guess, but I would like to make it invisible one way or the other. Is an adding flag for this a better option?

**Comment by nwg-piotr** [comment]
> but I would like to make it invisible one way or the other

It should be invisible by default. Isn't it on your side?

**Comment by clanktron** [comment]
Yea, I'll open an issue in nixpkgs for it. Thanks for your quick responses!
