### ISSUE TITLE
-d option: Move the mouse pointer to expected dock location for the dock to show up

### ISSUE THREAD

**Issue by geekthought** [nwg-piotr/nwg-dock#47]
i really prefer this option instead of pressing a key but, its hard to find the exact spot. The expected location or trigger should be much bigger. Its hit and miss the way it is now. Maybe i am doing something wrong?

**Comment by nwg-piotr** [comment]
The pointer speed is important. Moving it slowly won't launch the dock. Otherwise you wouldn't be able to access the screen part in this place.
