### ISSUE TITLE
[Question] animation support

### ISSUE THREAD

**Issue by Itstatertots** [nwg-piotr/nwg-dock#48]
just wondering if there is animation support or if theres plans to include it in a future update

**Comment by nwg-piotr** [comment]
What animation do you mean?

**Comment by Itstatertots** [comment]
like on macos when you hover over the hot spot it slides up instead of just appering

**Comment by Itstatertots** [comment]
also i just realized that i meant to post this in the hyprland repo not the sway one

**Comment by nwg-piotr** [comment]
Well, I'm not really keen on stuff like this. Maybe one day I'll buy a 6-pack and try to play with it. No ETA, however.

**Comment by Itstatertots** [comment]
completely fair one last question while i got u here is there a way to scale the icons when you hover over them with mouse?

**Comment by nwg-piotr** [comment]
Not really. You can set various `button:hover {}` attributes, but not dimensions.

**Comment by Itstatertots** [comment]
damn thats disappointing thank you tho

**Comment by nwg-piotr** [comment]
There's also no direct way to do it in the code, as one can set an image for a button, but can not change its size. To implement such a feature I'd have to change the icon image on each button hover. Doable, but quite complicated and inelegant.

**Comment by Itstatertots** [comment]
all good i it isnt rly a huge thing for me i was just wondering if its possible
