### ISSUE TITLE
Compile error with Debian

### ISSUE THREAD

**Issue by rbutoi** [nwg-piotr/nwg-dock#5]
With Debian testing, getting the following build error (can build fine on Arch Linux):

```
$ make get
go get github.com/gotk3/gotk3@289cfb6dbf32de11dd2a392e86de4a144ac6be48
go get github.com/gotk3/gotk3/gdk
go: found github.com/gotk3/gotk3/gdk in github.com/gotk3/gotk3
v0.5.3-0.20210223154815-289cfb6dbf32
go get github.com/gotk3/gotk3/glib
go: found github.com/gotk3/gotk3/glib in github.com/gotk3/gotk3
v0.5.3-0.20210223154815-289cfb6dbf32
go get github.com/dlasky/gotk3-layershell/layershell
go: found github.com/dlasky/gotk3-layershell/layershell in github.com/dlasky/gotk3-layershell
v0.0.0-20210331230524-5cca0b819261
# github.com/dlasky/gotk3-layershell/layershell
../../.go/pkg/mod/github.com/dlasky/gotk3-layershell@v0.0.0-20210331230524-5cca0b819261/layershell/layer.go:93:35:
could not determine kind of name for C.GtkLayerShellKeyboardMode
../../.go/pkg/mod/github.com/dlasky/gotk3-layershell@v0.0.0-20210331230524-5cca0b819261/layershell/layer.go:93:2:
could not determine kind of name for C.gtk_layer_set_keyboard_mode
make: *** [Makefile:5: get] Error 2
```

libgtk-layer-shell-dev 0.5.2-1, go1.15.9

Worth asking @dlasky too

**Comment by nwg-piotr** [comment]
@rbutoi BTW I also remember having this issue on Debian (Buster): https://github.com/gotk3/gotk3/issues/693

**Comment by dlasky** [comment]
It looks like that method was introduced on .6.0 of gtk layer shell library:

https://github.com/wmww/gtk-layer-shell/blob/master/include/gtk-layer-shell.h#L343

we could try adding some conditional feature detection so it builds but I'm not sure  how this would affect your app functionally @nwg-piotr

**Comment by nwg-piotr** [comment]
I gave up on keyboard in the dock, so it's not a problem. However, it would be better to keep up with the gtk-layer-shell development. @rbutoi - isn't it possible have a recent version on Debian?

**Comment by dlasky** [comment]
It's pretty easy to build from source which is what I was doing before it landed in aur. 

Lmk if you want me to write bindings for the version detection

**Comment by nwg-piotr** [comment]
Let's wait for the @rbutoi 's response.

**Comment by rbutoi** [comment]
Ah, thanks for the pointers, both! It it, indeed, very easy to build gtk-layer-shell, and it let me compile nwg-dock here.

**Comment by dlasky** [comment]
Glad to help (and that it worked!) cheers

**Comment by nwg-piotr** [comment]
Many thanks, Dan!
