### ISSUE TITLE
FreeBSD compile error gtk-layer-shell pango library error

### ISSUE THREAD

**Issue by justfly1111** [nwg-piotr/nwg-dock#7]
Pango_attr_insert_hyphens_new undefined error I’m sure you’ve seen this error on Linux build it carries over to bad I’m to get it to build by rewriting parts of the pango header file but haven’t had any luck yet

**Comment by nwg-piotr** [comment]
Well, it comes from the gotk3 library. See https://github.com/gotk3/gotk3/issues/693

For possible solution take a look at #5.

**Comment by justfly1111** [comment]
i didnt see the previous response =im going to check it out now thank you in advance

**Comment by justfly1111** [comment]
ya   i  checked thhat out prior to opening the issue. i havent had any luck even with changing  the v to 0.5.0 that builds fine seperatelt but for your project ieven if its building v.0.5.0 when it pulls in gotk3/pango and the subfolders of gotk3 the sub folders end up getting the updated code with the hyphen attr in it i spnt half the day trying to manually add it into my pango headers even replacing the headers with the new version headers andhavent any luck with it at all hopefully someone pops up that has sucessfully compiled it on freebsd current

**Comment by nwg-piotr** [comment]
Sorry, I know nothing about BSD. Must give it a try one day. I can only say that I've already seen a similar error, while trying to build my other gotk3-based stuff on Debian Buster.

**Comment by justfly1111** [comment]
have you been able to find a work around ?

**Comment by nwg-piotr** [comment]
I didn't try hard, to be honest. I thought that Debian users should be used to waiting for the latest stuff to work on their system. ;)

**Comment by jbeich** [comment]
gotk3 tries to bind to a symbol too for system pango package. Instead of [waiting for downstream](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=249879) simply remove the specific binding unused by nwg-dock e.g.,
```diff
--- ~/go/pkg/mod/github.com/gotk3/gotk3@v0.5.3-0.20210223154815-289cfb6dbf32/pango/pango-attributes.go~
+++ ~/go/pkg/mod/github.com/gotk3/gotk3@v0.5.3-0.20210223154815-289cfb6dbf32/pango/pango-attributes.go
@@ -187,13 +187,6 @@ func (v *Attribute) native() *C.PangoAttribute {
 	return (*C.PangoAttribute)(unsafe.Pointer(v.pangoAttribute))
 }
 
-func AttrInsertHyphensNew(insertHyphens bool) *Attribute {
-	c := C.pango_attr_insert_hyphens_new(gbool(insertHyphens))
-	attr := new(Attribute)
-	attr.pangoAttribute = c
-	return attr
-}
-
 /*
 //typedef gboolean (*PangoAttrFilterFunc) (PangoAttribute *attribute,
 //					 gpointer        user_data);
```

**Comment by jbeich** [comment]
Maybe close as [FreeBSD package](https://www.freshports.org/x11/nwg-dock) is available.

**Comment by nwg-piotr** [comment]
Great news. Thank you very much!
