### ISSUE TITLE
Dock's borders are shown when hidden

### ISSUE THREAD

**Issue by indicozy** [nwg-piotr/nwg-dock#8]
**Describe the bug**
Dock's borders are shown when hidden, and when the dock is shown that hidden border is overlapping with shown dock.
**To Reproduce**
1. change window{background-style} to solid and give proper width and color;
2. call "nwg-dock -d"
4. See this bug

**Expected behavior**
No visible borders when hidden, and no "hidden" borders to overlap the shown dock

**Screenshots**
<a href="https://ibb.co/3RfxB5C"><img src="https://i.ibb.co/FHsQgkD/screenshot-2021-05-06-14-06-35.png" alt="screenshot-2021-05-06-14-06-35" border="0"></a>
<a href="https://ibb.co/87Nx6hw"><img src="https://i.ibb.co/LZYgnGy/screenshot-2021-05-06-14-06-45.png" alt="screenshot-2021-05-06-14-06-45" border="0"></a>
or links:
```
https://ibb.co/3RfxB5C
https://ibb.co/87Nx6hw
```
**My Linux Build:**
 - Arch Linux
 - go 2:1.16.3-1
 - gtk-layer-shell 0.6.0-1

 P.S. I love your works, keep it going!

**Comment by nwg-piotr** [comment]
Thank you!

Could you please edit `/usr/share/nwg-dock/hotspot.css` and add `border: none` ? I'm at work at the moment and I can't check it myself now. 

```css
window {
  background-color: rgba (0, 0, 0, 0);
  border: none
}
```

**Comment by indicozy** [comment]
Yes, that worked, will you add that to the master branch?

**Comment by nwg-piotr** [comment]
Sure, as soon as I'm back at my own desk.
